"""
Defines constants for semantic strings (e.g. keys to dictionaries). These should be used to avoid string programming
and the hazards of that, e.g. unchecked typos in strings.
"""
BATCH_SIZE = 'batch_size'
CATEGORIES = 'categories'
CHECKPOINT_STEP = 'checkpoint_step'
CONFIG_FILE = 'config_file'
CONTINUE = 'continue'
CPU = 'cpu'
CUDA = 'cuda'
DATA = 'data'
DATASET = 'dataset'
DEV = 'dev'
DEBUG = 'debug'
DEVICE = 'device'
EPOCH_NUMBER = 'epoch_number'
EXPERIMENT_ID = 'experiment_id'
EXPORT_DIR = 'export_dir'
INPUT_SYMBOLS = 'input_symbols'
LANGUAGE_FAMILIES = 'language_families'
LANGUAGE_INFO_FILE = 'language_info_file'
LANGUAGES = 'languages'
LR = 'lr'
LR_DECAY = 'lr_decay'
LR_STEP_SIZE = 'lr_step_size'
MAIN = 'main'
MODEL_ARCHITECTURE = 'model_architecture'
NO_GPU = 'no_gpu'
NUM_EPOCHS = 'num_epochs'
NUM_FAMILIES = 'num_families'
NUM_LANGUAGES = 'num_languages'
OPTIMIZER = 'optimizer'
ORDERING = 'ordering'
OUTPUT_SYMBOLS = 'output_symbols'
SIGMORPHON2020 = 'sigmorphon2020'
SIGMORPHON2020_ROOT = 'sigmorphon2020_root'
TAGS = 'tags'
TEST = 'test'
TRAIN = 'train'
WANDB_DISABLED = "disable_wandb"
WANDB_DIRECTORY = "wandb_directory"
